### Utilization Analysis
---
This notebook has the utilization formula to get the current state an organization in terms of percentage of utilization per customer and per vehicle.

### Variables identification
- N. of Customers
- N. of Reservations average per Customer
- Average of reservation duration
- N. of Vehicles
- Available Hours

### Common Utilization Formula
\begin{gather*}
Utilization=\ \frac{Total\ Hours\ Vehicles\ are\ Reserved\ in\ a\ Month\ }{Total\ Available\ Vehicle\ Hours\ in\ a\ Month} \times 24
\end{gather*}

### Final Utilization Formula
\begin{equation*}
Utilization( \%) \ =\ \frac{Number\ of\ Customers\times Reservations\ per\ Customer\ per\ Month\ \times Average\ Reservation\ Duration\ Hours\ }{Number\ of\ Vehicles\times (720\ hours - Average\ Hours\ Inshop)} \times 100
\end{equation*}

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Read the CSVs
customers = pd.read_csv('data/n_customers.csv')
reservations_per_customer = pd.read_csv('data/n_reservation_per_customer.csv')
reservation_duration_hours = pd.read_csv('data/reservations_duration_hours.csv')
total_hours_vehicles_inshop_per_month = pd.read_csv('data/total_hous_vehicles_inshop_per_month.csv')

In [3]:
# Number of customers ACTIVE in JFS
customers.count()
# 

user_id    202
dtype: int64

In [4]:
# Statistical analysis for number of reservations per customer per month
reservations_per_customer['number_reservations'].describe()

count    2314.000000
mean       10.882022
std         6.846056
min         1.000000
25%         5.000000
50%        11.000000
75%        17.000000
max        35.000000
Name: number_reservations, dtype: float64

In [5]:
# Statistical analysis for the duration of reservations in hours
reservation_duration_hours.describe()

duration_hours
count    25181.000000
mean         8.992348
std         50.892716
min          0.000830
25%          3.653842
50%          6.029389
75%          7.776328
max       7248.198151

In [6]:
# Statistica analysis for the duration of vehicles INSHOP in hours per month
total_hours_vehicles_inshop_per_month['duration_hours'].describe()

count     54.000000
mean     209.991725
std      186.296776
min        0.085040
25%       96.799082
50%      165.939970
75%      257.669646
max      743.999722
Name: duration_hours, dtype: float64

### Variables Definition
- Number of Active Customers: **173**
- Average of reservations per customer per month: **10.882022**
- Average of the duration in hours of reservations: **8.992348**
- Number of vehicles in the fleet: **59**
- Average of hours a vehicle is in maintenance per month: **209.991725**
- Utilization: **35.15 %**

### Calculation of the Utilization Step by Step

\begin{equation*}
Total\ Reserved\ Hours\ =\ Number\ of\ Customers\times Reservations\ per\ Customer\ per\ Month\ \times Average\ Reservation\ Duration\ Hours\
\end{equation*}
\begin{equation*}
Total\ Reserved\ Hours\ =\ 19,766.69\ Hours\\
\end{equation*}

In [35]:
total_reserved_hours_per_month = 173 * 10.882022 * 8.992348
print(f'{total_reserved_hours_per_month} hours')

16928.902676804486 hours


\begin{equation*}
Available\ Hours\ per\ Vehicle\ per\ Month\ =\ 720\ Hours\ - Average\ Maintenance\ Duration\ In\ Hours\
\end{equation*}
\begin{equation*}
Available\ Hours\ per\ Vehicle\ per\ Month\ =\ 510.00\ Hours\
\end{equation*}

In [36]:
available_vehicle_hours_per_month = 720 - 209.991725
print(f'{available_vehicle_hours_per_month} hours')

510.008275 hours


\begin{equation*}
Total Available\ Vehicle\ Hours\ per\ Month\ = Number\ of\ Vehicles\ \times Available\ Hours\ per\ Vehicle\ per\ Month\
\end{equation*}
\begin{equation*}
Total Available\ Vehicle\ Hours\ per\ Month\ = 30,090.488\ Hours\
\end{equation*}

In [37]:
# Total available vehicle hours per month
total_available_vehicle_hour_per_month = 70 * 687.86
print(f'{total_available_vehicle_hour_per_month} hours')

48150.200000000004 hours


\begin{equation*}
Utilization\ ( \% per\ month ) =\ \frac{Total\ Reserved\ Hours\ }{Total\ Available\ Vehicle\ Hours\ } \times 100
\end{equation*}
\begin{equation*}
Utilization\ ( \% per\ month ) =\ 65.69\ \%
\end{equation*}

In [38]:
# Utilization (%)
utilization = (total_reserved_hours_per_month / total_available_vehicle_hour_per_month) * 100
print(f'Utilization is {utilization} %')

Utilization is 35.158530342147046 %


In [14]:
total_hours_inshop = pd.read_csv('data/hours_inshop_TFS.csv')


In [15]:
total_hours_inshop['duration_hours'].describe()

count    18704.000000
mean       162.419117
std        227.130477
min          0.001236
25%          6.090922
50%         53.293133
75%        213.348563
max        743.999722
Name: duration_hours, dtype: float64